# need env: NPM_TOKEN add at to action secrets, npm token doc see https://docs.npmjs.com/about-access-tokens/
name: node-release

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: |
          node -v
          npm install
          npm test
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
  node-gh-release:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get version and conventional
        id: check-version
        uses: convention-change/conventional-version-check@v1.2.0 # or change to latest version
        with:
          sha-length: 8

      - uses: softprops/action-gh-release@master
        name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          ## with permissions to create releases in the other repo
          token: "${{ secrets.GITHUB_TOKEN }}"
          body: "${{ steps.check-version.outputs.cc-latest-changes-log }}"
          #  body_path: ${{ github.workspace }}-CHANGELOG.txt
          prerelease: true
          # https://github.com/isaacs/node-glob
          # files: |
          #   **/*.tar.gz
          #   **/*.sha2566
