# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node-ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - '*-feature-*'
      - 'BF-*'
      - '*-bug-*'
      - 'PU-*'
      - 'DOC-*'
      - '*-documentation-*'
      - '*-hotfix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    # branches:
    #   - 'main'
    #   - 'release-*'
    #   - 'DOC-*'
    #   - 'hotfix-*'

jobs:
  node-ci:
    name: node-ci
    strategy:
      matrix:
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
         - '18.x'
         - '20.x'
         - 'lts/*'
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      -
        name: Install dependencies
        run: |
          node --version
          npm --version
          npm install

      -
        name: Build if present
        run: npm run build --if-present

      -
        name: run style check
        run: npm run format:check

      -
        name: run lint
        run: npm run lint

      -
        name: run test
        run: npm run test

      -
        name: Test coverage
        run: npm run jest:coverage
